steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m','cp','-r','gs://${_BUCKET_NAME}/builds/${_AGENT_ID}/*','.']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--no-invoker-iam-check'
      - '--platform'
      - 'managed'
      - '--network=default'
      - '--subnet=redis-subnet'
      - '--vpc-egress=private-ranges-only'

logsBucket: 'gs://build-logs'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}'

options:
  logging: LEGACY

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'langchain-agent-repo'
  _SERVICE_NAME: 'agent-default'
  _BUCKET_NAME: 'agentcore-465415_cloudbuild'
  _AGENT_ID: 'agent-default'
  _USER_EMAIL: ''
